---
title: "Бэктики"
output: html_document
---

Стоят пассажиры в аэропорту, посадочный досмотр проходят. Дошла очередь до мужика с чемоданом.

--- Пожалуйста, приготовьте чемодан к осмотру.

--- Не могу.

--- Почему?

--- А у меня там бэктики!

--- А что это?

--- Ну, отсосёте --- покажу!

Служба безопасности шутку не поняла, вызвала наряд полиции:

--- Гражданин, открывайте чемодан.

--- Но я не могу!

--- Почему не можете?

--- Потому что у меня там бэктики!

--- «Бэктики»? Что это?

--- Так отсосите мне, и я покажу!

Отобрали чемодан, а открыть никто не может. Повезли мужика в СИЗО. В камере сидельцы расспрашивают:

--- Братуха, за что тебя?

--- Да чемодан отказался открывать.

--- А что там?

--- Да бэктики там.

--- Какие нахуй «бэктики»?

--- Ну отсосите мне, тогда и расскажу.

И вот угодил мужик в лазарет, с побоями да синяками по всему телу, весь перебинтован, еле дышит. Следователи вызвали группу специалистов для вскрытия чемодана. Час, два, три пыхтели. Кое-как разворотили, смотрят --- а там `бэктики`.

[Авторка](https://t.me/stats_for_science)

[Ситуация создания](https://agency.blastim.ru/stat_r)

[Оригинал](https://baneks.site/%D1%81%D1%82%D0%BE%D1%8F%D1%82-%D0%BF%D0%B0%D1%81%D1%81%D0%B0%D0%B6%D0%B8%D1%80%D1%8B-%D0%B2-%D0%B0%D1%8D%D1%80%D0%BE%D0%BF%D0%BE%D1%80%D1%82%D1%83-%D0%BF%D0%BE%D1%81%D0%B0%D0%B4%D0%BE%D1%87%D0%BD%D1%8B%D0%B9-%D0%B4%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80/?p=4)



